services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
      - "${WEB_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=print-queue
      - API_PORT=3000
      - WEB_PORT=8080
      - UPLOADS_DIR=/app/uploads
    volumes:
      - ${UPLOADS_HOST_DIR:-../uploads}:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: